### ISSUE TITLE
pkg-config reports wrong paths for qmqtt

### ISSUE THREAD

**Issue by cecilios** [emqtt/qmqtt#104]
I have installed the library by doing:
```
cd ..../qmqtt-master
mkdir build && cd build
sudo qmake ../src/mqtt/
sudo make install
```
and seems to work. This is the final part of the log, displaying installation paths:

```
   ...

ln -s libqmqtt.so.1.0.0 libqmqtt.so
ln -s libqmqtt.so.1.0.0 libqmqtt.so.1
ln -s libqmqtt.so.1.0.0 libqmqtt.so.1.0
rm -f /lib/libqmqtt.so.1.0.0
mv -f libqmqtt.so.1.0.0  /lib/ 
rm -f /lib/libqmqtt.so
rm -f /lib/libqmqtt.so.1
rm -f /lib/libqmqtt.so.1.0
mv -f libqmqtt.so /lib/ 
mv -f libqmqtt.so.1 /lib/ 
mv -f libqmqtt.so.1.0 /lib/ 
install -m 755 -p "/lib/libqmqtt.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libqmqtt.so.1.0.0"
ln -f -s "libqmqtt.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libqmqtt.so"
ln -f -s "libqmqtt.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libqmqtt.so.1"
ln -f -s "libqmqtt.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libqmqtt.so.1.0"
sed -e s,/include,/usr/include/x86_64-linux-gnu/qt5,g -e s,/lib,/usr/lib/x86_64-linux-gnu,g "/lib/libqmqtt.prl" >"/usr/lib/x86_64-linux-gnu/libqmqtt.prl"
sed -e s,/include,/usr/include/x86_64-linux-gnu/qt5,g -e s,/lib,/usr/lib/x86_64-linux-gnu,g "/lib/libqmqtt.la" >"/usr/lib/x86_64-linux-gnu/libqmqtt.la"
sed -e s,/include,/usr/include/x86_64-linux-gnu/qt5,g -e s,/lib,/usr/lib/x86_64-linux-gnu,g "/lib/pkgconfig/qmqtt.pc" >"/usr/lib/x86_64-linux-gnu/pkgconfig/qmqtt.pc"
install -m 644 -p /include/qmqtt/qmqttDepends /usr/include/x86_64-linux-gnu/qt5/qmqtt/
install -m 644 -p /mkspecs/modules-inst/qt_lib_mqtt.pri /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/
install -m 644 -p /mkspecs/modules-inst/qt_lib_mqtt_private.pri /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/
install -m 644 -p /lib/cmake/Qt5qmqtt/Qt5qmqttConfig.cmake /usr/lib/x86_64-linux-gnu/cmake/Qt5qmqtt/
install -m 644 -p /lib/cmake/Qt5qmqtt/Qt5qmqttConfigVersion.cmake /usr/lib/x86_64-linux-gnu/cmake/Qt5qmqtt/
```

But pkg-config reports wrong paths. For instance:

```
$ pkg-config qmqtt --cflags 
-I/usr/usr/include/x86_64-linux-gnu/qt5/x86_64-linux-gnu/qt5/qmqtt -I/usr/usr/include/x86_64-linux-gnu/qt5/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork

```

pkg-config points to '-I/usr/usr/include/x86_64-linux-gnu/qt5/x86_64-linux-gnu/qt5/qmqtt'
but the files were installed in '/usr/include/x86_64-linux-gnu/qt5/x86_64-linux-gnu/qt5/qmqtt'. Note an extra '/usr/' at beginning and duplicated 'x86_64-linux-gnu/qt5' folders.

This is the installed qmqtt.pc file:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu
includedir=${prefix}/usr/include/x86_64-linux-gnu/qt5/x86_64-linux-gnu/qt5


Name: qmqtt
Description: qmqtt module
Version: 1.0.0
Libs: -L${libdir} -lqmqtt 
Libs.private: -lQt5Network -L/usr/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu -lQt5Core -lpthread   
Cflags: -I${includedir}/qmqtt -I${includedir}
Requires: Qt5Core Qt5Network
```

As can be seen `prefix=/usr` creates a duplicate '/usr' folder in the paths. Also the paths have duplicated 'x86_64-linux-gnu/' and 'qt5'. A second issue is that folder '/usr/include/x86_64-linux-gnu/qt5/qmqtt' does not contain the headers for qmqtt bu just a file named 'qmqttDepends'. Are header files not copied during qmqtt library installation?.

All this need to be reviewed and fixed.

**Comment by mwallnoefer** [comment]
@ejvr @KonstantinRitt @emqtt/qmqtt-team I think you are the experts of qmqtt's build system. Please read this issue and answer!

**Comment by ejvr** [comment]
Running `qmake ../src/mqtt/` was not a good idea. Unfortunately I could not test it on my own system when I wrote the comment. You have to revert to `qmake ..`. If you stick to that, qmqtt.pc looks like this:
```
prefix=/home/ej/extern/Qt/5.9.1/gcc_64
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: qmqtt
Description: qmqtt module
Version: 1.0.0
Libs: -L${libdir} -lqmqtt 
Cflags: -I${includedir}/qmqtt -I${includedir}
Requires: Qt5Core Qt5Network
```
That seems OK to me. Note that I installed QT 5.9.1 using [QT online installer](https://www.qt.io/download-open-source/#section-2) provided by QT itself. The QT install root was `/home/ej/Qt`.

Which means we are back to issue #103 again.

**Comment by mwallnoefer** [comment]
I close this for now.

**Comment by cecilios** [comment]
Please accept my sincere apologies for the long delay in the reply to your messages; they came in while I was on vacation.

When building qmqtt according to instructions in issue #103 the paths reported by pk-config are correct. So, probably nothing wrong with pk-config generation and this issue can be definitely closed.
