### ISSUE TITLE
QMQTT with websockets

### ISSUE THREAD

**Issue by vinayxbox** [emqtt/qmqtt#107]
I have setup eMQTT in windows I am using QMQTT for subscription and publishing.

Everything works like a charm.

My problem is how to use websocket with QMQTT Client.

There are no methods in QMQTT::Client which accepts URL.

I tried to use hostname,/host address with port 8083 default for ws port for broker but not able to connect.

Can anybody help me in this?
 Seems like I am doing something wrong.

**Comment by mwallnoefer** [comment]
I do not think that this is currently supported, since the library is based on _QTcpSocket_.

If you like to code, you could add this support to the library and propose a patch.

**Comment by mwallnoefer** [comment]
Fixed by commit  3b22b35 (pull request #119).
