### ISSUE TITLE
connect to host failed

### ISSUE THREAD

**Issue by HereIsTino** [emqtt/qmqtt#120]
isConnectedToHost() always return false, why?
this is my code:
QMQTT::Client *client = new QMQTT::Client(QHostAddress::LocalHost, 1883);
client->setUsername("user");
client->setPassword("password");
client->setClientId("clientId");
if(client->isConnectedToHost()) {
    ...
   connect sucessfule
}else {
   ...
   connect to failed
}

thank you.

**Comment by ejvr** [comment]
After setting username, password and client ID you should call the `connectToHost` function. This will initiate the connection procedure. Calling `isConnectedToHost` directly after that will still return false. When a connection has been established, the `connected` signal is emitted and `isConnectedToHost` will return `true`.

The best thing to do is to connect to the `connected` to a slot in your code, and put to code you want to execute after connecting there.
