### ISSUE TITLE
cannot connect to MQTT broker

### ISSUE THREAD

**Issue by sarangborude** [emqtt/qmqtt#123]
Hi I am using CloudMQTT as the MQTT broker
I have a username and password to access.
My code looks like following
QMQTT::Client *client = new QMQTT::Client();
    client->setUsername("username");
    client->setPassword("password");
    client->setHostName("mqtt://m11.cloudmqtt.com");
    client->setPort(port);
client->connectToHost();
client->connectionState() (This returns 0)

Why could this be happening
What is the best way to specify hostname?

Thanks,
Sarang

**Comment by mwallnoefer** [comment]
Please look at issue #120 to find the answer.

**Comment by ejvr** [comment]
Also, drop the 'mqtt://' prefix from the hostname. It is a hostname after all, not a url.
