### ISSUE TITLE
WebSocket cannot disconnectFromHost

### ISSUE THREAD

**Issue by hyo0913** [emqtt/qmqtt#124]
QMQTT::WebSocket::disconnectFormHost() has a bug

line 45: _socket->disconnect(); (call diconnect function of QObject)
have to change like this
_socket->close();

**Comment by mwallnoefer** [comment]
@ejvr I think this is a serious issue. Would you like to fix it since you are the one which contributed the websocket part?

**Comment by ejvr** [comment]
@mwallnoefer  Yes, this is a serious problem. Just posted a pull request to fix this.
Thanks @hyo0913
