### ISSUE TITLE
Compatibility with cloudqmtt.com?

### ISSUE THREAD

**Issue by jfitz1959** [emqtt/qmqtt#128]
I've pulled the code, and incorporated all  the example code into an existing GUI app (QT 5.7 ). All sample code compiles/links and the app runs fine 
Implementing this section....
Subscriber subscriber;
subscriber.connectToHost();
Publisher publisher;
publisher.connectToHost();

my app never exits. Closer inspection shows the connect slot is never fired.

I've also tried this on a working mqtt connection (cloudmqtt.com):
        QHostInfo info = QHostInfo::fromName("m14.cloudmqtt.com");
        QMQTT::Client *client = new QMQTT::Client(info.addresses().first(), 17750);
        client->setClientId("publisher");
        client->setUsername("x...b");
        client->setPassword("r..m");
        client->connectToHost();
        client->publish(QMQTT::Message(1,QString("mqttdotnet/out"),QByteArray("message test from qt")));

Again I never see the connection being made... I know this is a broad question, but is there any other broader issue with respect to QT and TCP sockets that I should be concerned with?
This appears to be a well done implementation of the MQTT protocol and I would love to try some IOT ideas upon it.

**Comment by mwallnoefer** [comment]
@ejvr Have you had already a look on this?

**Comment by ejvr** [comment]
Not really. Maybe I have some time in the weekend to play around with CloudMqtt.

My guess is that CloudMqtt needs an SSL connection, because it is a cloud service. You would not want to transmit username & password in clear text over the internet. But I'm not completely sure if that is how CloudMqtt works. It's is also possible they support websockets only (so no TCP or TCP+SSL).

A quick visit to the cloud MQTT website was not enough to find the answer.

@jfitz1959 You are trying to make a unencrypted connection to CloudMqtt. Maybe this is not supported. So you could try SSL or websockets (see the README for some info on how to do that).

**Comment by jfitz1959** [comment]
@mwallnoefer I'll give the SSL technique a try out. side note: the MQTTLib for .NET works fine on the same machine. Thanks for the feedback.

**Comment by ejvr** [comment]
I had some time to take a look at CloudMqtt. It appears they do support connections over unencrypted TCP.
I managed to get a working connection by adjusting the example project. The project now also contains a very simple GUI. It looks like this:
```
int main(int argc, char** argv)
{
    QApplication app(argc, argv);

    QMainWindow w;
    app.setActiveWindow(&w);

    QList<QHostAddress> ipadresses = QHostInfo::fromName(Hostname).addresses();
    Subscriber subscriber(ipadresses.front(), TcpPort);
    subscriber.setUsername(Username);
    subscriber.setPassword(Passwd);
    subscriber.connectToHost();
    Publisher publisher(ipadresses.front(), TcpPort);
    publisher.setUsername(Username);
    publisher.setPassword(Passwd);
    publisher.connectToHost();

    w.show();

    return app.exec();
}
```

@jfitz1959 Can you try to run this? If this works, but your own project does not, maybe you could check if the mainloop is active (that is: if the application is idle, a call to QApplication::exec should be on the stack). If the mainloop is not active, incoming data from the mqtt connection will not be handled.
