### ISSUE TITLE
connect localhost error

### ISSUE THREAD

**Issue by 841974180** [emqtt/qmqtt#129]
QMQTT::Client *client = new QMQTT::Client(QHostAddress::LocalHost);
    client->connectToHost();
    if(!client->isConnectedToHost())
    {
        qDebug()<<"falied";
    }
    QObject::connect(client,&QMQTT::Client::error,[](const QMQTT::ClientError error){
        qDebug()<<error;
    });

the log is  falied  , the error enum is 1 ClientError::SocketConnectionRefusedError

**Comment by ejvr** [comment]
The reason for the first log message ("failed") is simple: isConnectedToHost is asynchronous. 
The function call only starts the connection procedure, the connected signal will be emitted
after the connection has been made.

The reason for the SocketConnectionRefusedError: I'm not sure, but the error suggests that there
is no mqtt server running on localhost, or the port number is incorrect.

On 06-Mar-18 03:29:38, 星夜无月 <notifications@github.com> wrote:
QMQTT::Client *client = new QMQTT::Client(QHostAddress::LocalHost);
client->connectToHost();
if(!client->isConnectedToHost())
{
qDebug()<<"falied";
}
QObject::connect(client,&QMQTT::Client::error,[](const QMQTT::ClientError error){
qDebug()<<error;
});
the log is falied , the error enum is 1 ClientError::SocketConnectionRefusedError

**Comment by 841974180** [comment]
hi,ejvr.Thanks for your caution,I think I don't set up mqtt server.The other things I use this lib to connect the net mqtt server the default constructor (QHostAddress,port,QObject) cann't connect, when I try other constructor(QString address, port, bool ssl, bool ..., ...) I success,but I don't understand why.

**Comment by ejvr** [comment]
Hallo 星夜无月,

Hmm, it appears you are right. It seems that the constructor (QHostAddress,port,QObject) always tries to connect to localhost, which is a bug of course. I will look into it.

Thanks for sharing your observation!
On 07-Mar-18 01:33:57, 星夜无月 <notifications@github.com> wrote:
hi,ejvr.Thanks for your caution,I think I don't set up mqtt server.The other things I use this lib to connect the net mqtt server the default constructor (QHostAddress,port,QObject) cann't connect, when I try other constructor(QString address, port, bool ssl, bool ..., ...) I success,but I don't understand why.

**Comment by mwallnoefer** [comment]
Good catch, @ejvr. I have merged the fix and close the issue.
