### ISSUE TITLE
qmqtt- cannot connect to host

### ISSUE THREAD

**Issue by KishoreRavih** [emqtt/qmqtt#131]
I am having a problem in connecting to host using qmqtt. below is my code
QFile certFile("YOURPFXFILE.pfx");
bool rt = certFile.open(QFile::ReadOnly);
qDebug()<<"certificate opened succ"<<rt;
QSslCertificate certificate;
QSslKey key;
QList importedCerts;
QString passphrase = "virtual";
bool imported = QSslCertificate::importPkcs12(&certFile, &key, &certificate, &importedCerts, QByteArray::fromStdString(passphrase.toStdString()));

   certFile.close();

   qDebug() << "Imported cert:" << imported;
   QSslConfiguration sslConfig = QSslConfiguration::defaultConfiguration();

   if (imported) {
       QList<QSslCertificate> certs = sslConfig.caCertificates();
       QList<QSslCertificate> localCerts = sslConfig.localCertificateChain();
       localCerts.append(certificate);
       certs.append(importedCerts);

       sslConfig.setLocalCertificateChain(localCerts);
       sslConfig.setCaCertificates(certs);
       sslConfig.setPrivateKey(key);
       
       sslConfig.setProtocol(QSsl::TlsV1_2);
       sslConfig.setPeerVerifyMode(QSslSocket::AutoVerifyPeer);
       QSslConfiguration::setDefaultConfiguration(sslConfig);
   }
QMQTT::Client *client = new QMQTT::Client("xxxxx.us-east-1.amazonaws.com", 8883, sslConfig, false);
connect(client, SIGNAL(connected()), this, SLOT(onConnected()));
connect(client,SIGNAL(received(QMQTT::Message)), this, SLOT(onReceived(QMQTT::Message)));
connect(client, SIGNAL(subscribed(QString,quint8)), this, SLOT(onSubscribed(QString,quint8)));
connect(client,SIGNAL(error(QMQTT::ClientError)), this, SLOT(onClientError(QMQTT::ClientError)));

client->setKeepAlive(true);
client->setAutoReconnect(true);

client->connectToHost();
I am getting QMQTT::ClientError as SocketSslHandshakeFailedError.

Can you please help me to check what am I missing??
Thanks!!

**Comment by mwallnoefer** [comment]
@ejvr @KonstantinRitt  Do you have an idea?

**Comment by mwallnoefer** [comment]
@KonstantinRitt You are the SSL guy here, do you have no clue?

**Comment by mwallnoefer** [comment]
Closing since we got no answer for a while.
