### ISSUE TITLE
Need a way to set QSslConfiguration to WebSocket

### ISSUE THREAD

**Issue by jjhsieh** [emqtt/qmqtt#132]
There is no way to add custom SSL configuration when connecting with WebSocket.

The Qt5 doc says it can be done with this API:
http://doc.qt.io/qt-5/qwebsocket.html#setSslConfiguration

I have modified qmqtt and it worked:
[0001-Support-using-custom-QSslConfiguration-for-WebSocket.patch.zip](https://github.com/emqtt/qmqtt/files/1867672/0001-Support-using-custom-QSslConfiguration-for-WebSocket.patch.zip)

Could you help to add formal support on this?

Thanks.

**Comment by mwallnoefer** [comment]
A nice patch, @jjhsieh.

@ejvr @KonstantinRitt What do you think? Especially you Konstantin, which did much work in the SSL area, could you review and test it for us?

**Comment by KonstantinRitt** [comment]
looks good to me, though I'd propose s/QSslConfiguration*/const QSslConfiguration &/g and s/config != NULL/!config.isNull()/
