### ISSUE TITLE
Does qmqtt client support token authentication?

### ISSUE THREAD

**Issue by qwyinxiang** [emqtt/qmqtt#133]
My Mqtt broker need a token based authentication, I want to know does the qmqtt client support token based authentication? if support, how can I config?

**Comment by qwyinxiang** [comment]
I config the mqtt client as below:
client = new QMQTT::Client(QHostAddress(strHost), mqttPort);
client->setUsername(strAccessToken);
client->setKeepAlive(60);
client->connectToHost();
 my program crashed later.

**Comment by ejvr** [comment]
QMQTT only supports username/password combos. Maybe it is possible to create access tokens using another protocol (like OAUTH) and send them to the broker using the password field in the connect message (see [this](https://www.hivemq.com/blog/mqtt-security-fundamentals-oauth-2-0-mqtt) page for more info) This should work.

**Comment by qwyinxiang** [comment]
### I set my QMQTT client as below:      
        client->setHostName(strHost);
        client->setPort(mqttPort);
        gSysSetting->generateApplicationKey();
        gSysSetting->generateAccessToken();
        client->setClientId("manager");
        client->setPassword(gSysSetting->getAccessToken().toUtf8());
        client->setKeepAlive(60);
        client->connectToHost();
My Mqtt client disconnect immediately?

 ### Then, I set my mqtt client as below:
    client->setUsername(gSysSetting->getAccessToken().toUtf8());
   
My mqtt client still disconnect immediately?

**Comment by qwyinxiang** [comment]
Yes, qmqtt support token based authentication, I set the token using the username filed is correct.
Before, My mqtt client disconnect is because my mqtt topic's format is wrong.
thank you very much.

**Comment by mwallnoefer** [comment]
Regarding to pull request: #135. Is it fine that we modify an existing signal, e.g. change its interface by introducing a new parameter? I would avoid breaking existing code.

**Comment by yinbaoqiang** [comment]
The connack return value is divided by 0 except for success. The other is failure. The new signal can be used to maintain the previous compatibility. The signal before returning 0 will return the failed signal if it is non-zero. The ack value will be returned in the failure signal.

**Comment by mwallnoefer** [comment]
As far as I read in the official docs http://doc.qt.io/qt-5/signalsandslots.html, arguments to signals may be added without breaking existing code, so it should be okay.

@ejvr + @KonstantinRitt: Are you also fine with this change or do you propose something else?

**Comment by mwallnoefer** [comment]
@yinbaoqiang The modified pull request #138 has landed in our repo. Do you require something else in this ticket or may we close it?

**Comment by yinbaoqiang** [comment]
Now realize my needs, thank you.
