### ISSUE TITLE
How to detect heartbeat timeout?

### ISSUE THREAD

**Issue by yinbaoqiang** [emqtt/qmqtt#139]
I did not see the heartbeat timeout detection code in the source code. I only saw a signal void pingresp(). Do I need to receive the signal externally to handle the heartbeat timeout?

**Comment by mwallnoefer** [comment]
@ejvr?

**Comment by ejvr** [comment]
@yinbaoqiang is right. QMQTT will send a heartbeat (PINGREQ) on regular interval, and it will report the response (PINGRESP) sent by the server, but the absense of the response is not reported. So yes, this has to be done externally, right now.

According to the standard (MQTT-3.1.2-24), the client must close the connection if there is no response after 1.5x the keep alive interval. So in this respect QMQTT does not follow the standard.

It is fairly simple to fix this. I will take a look at the problem.

**Comment by yinbaoqiang** [comment]
@ejvr 
After (MQTT-3.1.2-24),

> If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.

1.5x is the server's processing method, not the client's processing method.

**Comment by ejvr** [comment]
You are correct. As far as I understand now, there is no timeout specified
for the client. What would you propose? I would take a percentage of the
keep alive interval.

**Comment by yinbaoqiang** [comment]
If no message is sent or received for a period of time, the PINGREQ command is sent. If a timeout period is set for the detection, and if the timeout period does not reach PINGRESP, the timeout is determined and the connection is disconnected and reconnected.

**Comment by mwallnoefer** [comment]
This should have been fixed by pull request #140.
