### ISSUE TITLE
SUBSCRIBE and UNSUBSCRIBE does not support multi-topic filters

### ISSUE THREAD

**Issue by yinbaoqiang** [emqtt/qmqtt#141]
> The payload of a SUBSCRIBE Packet contains a list of Topic Filters indicating the Topics to which the Client wants to subscribe. The Topic Filters in a SUBSCRIBE packet payload MUST be UTF-8 encoded strings as defined in Section 1.5.3 [MQTT-3.8.3-1]

> The payload for the UNSUBSCRIBE Packet contains the list of Topic Filters that the Client wishes to unsubscribe from. The Topic Filters in an UNSUBSCRIBE packet MUST be UTF-8 encoded strings as defined in Section 1.5.3, packed contiguously [MQTT-3.10.3-1].

I did not find the source code that supports this feature.

**Comment by mwallnoefer** [comment]
Okay, closing it since the feature will not be implemented.
