### ISSUE TITLE
Can not auto reconnect in raspberry pi

### ISSUE THREAD

**Issue by flashtt** [emqtt/qmqtt#144]
I write a demo in PC, and set AutoReconnnect to true. It works well. But the AutoReconnect function can not work when I use the demo in Raspberry Pi.  I could not find the problem because the codes are the same.

**Comment by ejvr** [comment]
With 'PC' do you mean Windows?

On 27-May-18 07:20:07, flashtt <notifications@github.com> wrote:
I write a demo in PC, and set AutoReconnnect to true. It works well. But the AutoReconnect function can not work when I use the demo in Raspberry Pi. I could not find the problem because the codes are the same.

**Comment by flashtt** [comment]
Sorry for late,  PC means Windows, actually the same demo in ubuntu desktop also works well.

**Comment by flashtt** [comment]
I register the error signal to  a slot, there are two circumstance for reference in raspberry pi.
First I run the demo without network. It prints error and connect successfully when I connect the network.
Second I run the demo with network connected. Then I disconnect the network, the slot doesn' t work, and so no reconnection happens when I recover the network.
I don't understand why it doesn't work. The pingresp signal can work.

**Comment by flashtt** [comment]
Thanks, I use a timer to detect connection status for a temporary solution. Indeed some signals not emit but I don't know why. I will post my program after further test, or maybe I can find the problem.

**Comment by mwallnoefer** [comment]
Closing it for now, please reopen if you feel the need, in particular when you have more details to give us.
