### ISSUE TITLE
Same module linking name as official qtmqtt module

### ISSUE THREAD

**Issue by tomasz3dk** [emqtt/qmqtt#145]
Both emqtt/qmqtt and official [QtMqtt](http://doc.qt.io/QtMQTT/index.html) module from Qt Company have same name to link against module in qmake *.pro file:

> QT += mqtt

**Comment by mwallnoefer** [comment]
@ejvr + @KonstantinRitt What could we do here? Is renaming the only possibility, although not nice since we break existing code?

**Comment by ejvr** [comment]
I think that is a good idea. This implies that we should no encourage people to use qmqtt with QT version that support QtMqtt (>= 5.10?). It older version there is no conflict (until someone backports QtMqtt).

**Comment by tomasz3dk** [comment]
I also think that this is a good idea, but also have some concerns that some people will probably want to use this implementation of mqtt module (which is very good btw) for license reason. QtMqtt is actually part of Qt for Automation offer from Qt Company which is paid. QtMqtt is also available on GPL license, so when someone wants to write closed source software must buy license from Qt Company. This is not a problem for me, just say about this. BTW thank you guys for your good work.

**Comment by spockfish** [comment]
I can say from my own experience, that this implementation works better than the official Qt one. Furthermore it has also more functionality (reconnect for example), so I really hope you guys are not going to abandon this. The licensing part is a huge issue.

I still would consider to rename the module from 'mqtt' to 'emqtt'. It's a relatively straight forward change that does not have that much impact when people upgrade.

**Comment by mwallnoefer** [comment]
> I still would consider to rename the module from 'mqtt' to 'emqtt'. It's a relatively straight forward change that does not have that much impact when people upgrade.

Before doing this I would like to hear some more opinions, since such a change affects basically all user projects.

**Comment by KonstantinRitt** [comment]
As long as emqtt project doesn't follow any BC policies and one have to rebuild the module from time to time, I (personally) don't care about the module name. Renaming it to `emqtt` sounds ok to me.

**Comment by tomasz3dk** [comment]
For me it also sounds ok.

**Comment by mwallnoefer** [comment]
@ejvr You were also very active here, what do you think about the rename?

**Comment by ejvr** [comment]
Apart from breaking some builds (which can be easily fixes) I so no problems in renaming the library. mqtt is just slightly too generic.

**Comment by mwallnoefer** [comment]
Okay, according to this comments people should be okay with this decision.

@KonstantinRitt Could you please prepare the rename patch so that I can merge it? I think it was you who has done the 'modularization'.

**Comment by KonstantinRitt** [comment]
@mwallnoefer Done as part of https://github.com/emqtt/qmqtt/pull/153

**Comment by mwallnoefer** [comment]
Fantastic @KonstantinRitt, thanks for the contribution.
