### ISSUE TITLE
Not connect to Host

### ISSUE THREAD

**Issue by jbenfica** [emqtt/qmqtt#148]
Hello, I would like help. I already compiled and installed the library, all right. The client example (which comes along) works perfectly. But when I create a project, it never connects. Below is my code, please help me.

#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <qmqtt.h>
#include <QCoreApplication>
#include <QTimer>

QHostAddress EXAMPLE_HOST;
const quint16 EXAMPLE_PORT = 1883;
const QString EXAMPLE_TOPIC = "temperatura";

QMQTT::Client *client = new QMQTT::Client(EXAMPLE_HOST, 1883);

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);   
  

    connect(client, SIGNAL(connected()), SLOT(onConnected()));
    connect(client, SIGNAL(disconnected()), SLOT(timer_teste()));    
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow:: timer_teste()
{
    qDebug() << "desconectado";
}
void MainWindow:: onConnected()
{   
    int _number=25;
    QMQTT::Message message(_number, EXAMPLE_TOPIC,QString("Number is %1").arg(_number).toUtf8());
    client->publish(message);
    qDebug() << "entrou";
}

void MainWindow::on_pushButton_2_clicked()
{
    EXAMPLE_HOST.setAddress("10.30.152.111");
    client->setClientId("clientId");
    client->setUsername("user");
    client->setPassword("password");   
    client->setHost(EXAMPLE_HOST);
    client->connectToHost();
    qDebug() <<"conectado = " << client->isConnectedToHost();
}

**Comment by mwallnoefer** [comment]
At first glance your code looks correct. But you would need to elaborate a bit more on this; e.g. did you test with some other mqtt client libraries using the same settings? Have you already tried connecting with our Qt GUI Client (https://github.com/emqtt/qmqtt-client)?

**Comment by jbenfica** [comment]
Hello!! Thanks for your help, yes I tried thes example (https://github.com/emqtt/qmqtt-client), same thing. 
It compiles, but never connects. 
Any other possibility???

**Comment by ejvr** [comment]
Hello,

First of all, I think it is a good idea to test with a local mqtt broker
first, so you can exclude all kinds of connection and authentication
problems.

It is also worth mentioning that the connectToHost function is
asynchronous. So your debug message right after will always tell you there
is no connection.

Also  check if there are any other debug msssages. For example, there may
be something wrong with your signal slot connections. Since you are using
the 'old fashioned' way to cknnect, any problems will show up in runtime
only.

**Comment by mwallnoefer** [comment]
> "Since you are using the 'old fashioned' way to connect" -> Is there another more correct way to make the connection ??

Yes, you can use the C++11 syntax:
```
connect(client, &QMQTT::Client::connected, this, &MainWindow::onConnected);
```
Please have a look at Qt's wiki page: http://wiki.qt.io/New_Signal_Slot_Syntax

**Comment by mwallnoefer** [comment]
Any news here?

**Comment by mwallnoefer** [comment]
Closing it for now.
