### ISSUE TITLE
Protocol display Any

### ISSUE THREAD

**Issue by genii2014** [emqtt/qmqtt#149]
> 1、I have a problem connecting MQTT server, server monitoring protocol display Any;

>2、Client  @Demo：
`QObject::connect(clientmqtt,` &QMQTT::Client::connected, this, &Publisher::onConneccted);
`void Publisher::onConneccted()
`{
`    qDebug() << "OnConnected~~~";
`    clientmqtt->subscribe(EXAMPLE_TOPIC, 0);
`    _timer.start(1000);
`}

>onConneccted ： Not receiving signal

>MQTT Server:   Apollo Console

**Comment by mwallnoefer** [comment]
At a first glance the code looks correct, but you would also need to tell us if you use the event queue etc. Maybe a more complete example could help us to diagnose this further.

Finally, could your issue be related to #148?

**Comment by genii2014** [comment]
**MQTTDemo.pro**

`QT += core`
`QT -= gui`
`QT += network`
`QT += websockets`

`CONFIG += c++11`
`CONFIG += console`
`CONFIG -= app_bundle`

`TARGET = MQTTDemo`
`TEMPLATE = app`
`SOURCES += main.cpp \`
`    publisher.cpp`
`HEADERS += \`
`    publisher.h`

`INCLUDEPATH += F:\Downlist\qmqtt-master\src\mqtt`
`LIBS += F:/Downlist/build-qmqtt-Desktop_Qt_5_7_0_MinGW_32bit-Debug/lib/libqmqtt.a \`
`        F:/Downlist/build-qmqtt-Desktop_Qt_5_7_0_MinGW_32bit-Debug/lib/libqmqttd.a`


**publisher.h**
```
#ifndef PUBLISHER_H
#define PUBLISHER_H

#include <QObject>
#include <qmqtt.h>
#include <QTimer>
#include <qnetWork.h>

class Publisher : public QObject
{
    Q_OBJECT
public:
    Publisher();

    Publisher(const QHostAddress& host,
                       const quint16 port,
                       QObject* parent = NULL);

    ~Publisher();
    QMQTT::Client* clientmqtt;
    QTimer _timer;
    quint16 _number;


public slots:
    void onConneccted();
    void onTimeout();
    void onDisconnected();
    void onErrer(const QMQTT::ClientError error);
    void onReceived(const QMQTT::Message& message);
};

#endif // PUBLISHER_H
```
**publisher.cpp**
```
#include "publisher.h"
const QHostAddress EXAMPLE_HOST = QHostAddress::LocalHost;
const quint16 EXAMPLE_PORT = 61613;
const QString EXAMPLE_TOPIC = "qmqtt/exampletopic";


Publisher::Publisher()
{
    clientmqtt = new QMQTT::Client(EXAMPLE_HOST, EXAMPLE_PORT );
    clientmqtt->setClientId("ClientID");
    clientmqtt->setUsername("admin");
    clientmqtt->setPassword("password");
    clientmqtt->setAutoReconnect(true);

    _number = 0;
    QObject::connect(clientmqtt, &QMQTT::Client::connected, this, &Publisher::onConneccted);
    QObject::connect(&_timer, &QTimer::timeout, this, &Publisher::onTimeout);
    QObject::connect(clientmqtt, &QMQTT::Client::disconnected, this, &Publisher::onDisconnected);
    QObject::connect(clientmqtt,&QMQTT::Client::error, this, &Publisher::onErrer);
    QObject::connect(clientmqtt, &QMQTT::Client::received, this, &Publisher::onReceived);
    clientmqtt->connectToHost();
}

Publisher::Publisher(const QHostAddress &host, const quint16 port, QObject *parent)
{

    clientmqtt = new QMQTT::Client(host, port);
    clientmqtt->setClientId("ClientID");
    clientmqtt->setUsername("admin");
    clientmqtt->setPassword("password");
    _number = 0;
    QObject::connect(clientmqtt, &QMQTT::Client::connected, this, &Publisher::onConneccted);
    QObject::connect(&_timer, &QTimer::timeout, this, &Publisher::onTimeout);
    QObject::connect(clientmqtt, &QMQTT::Client::disconnected, this, &Publisher::onDisconnected);

}

Publisher::~Publisher() { delete clientmqtt; }

void Publisher::onConneccted()
{
    qDebug() << "OnConnected~~~";
    clientmqtt->subscribe(EXAMPLE_TOPIC, 0);
    _timer.start(1000);
}


void Publisher::onTimeout()
{
    QMQTT::Message message(_number, EXAMPLE_TOPIC,
                           QString("Number is %1").arg(_number).toUtf8());
    clientmqtt->publish(message);
    _number++;
    qDebug() << _number;
    if(_number >= 10)
    {
        _timer.stop();
        clientmqtt->disconnectFromHost();
    }
}

void Publisher::onDisconnected()
{
    qDebug() << "Disconnected";
//    QTimer::singleShot(0, qApp, &QCoreApplication::quit);

}

void Publisher::onErrer(const QMQTT::ClientError error)
{
    qDebug() << error;
}

void Publisher::onReceived(const QMQTT::Message &message)
{
    qDebug() << "publish received: \"" << QString::fromUtf8(message.payload())
          << "\"" << endl;
}
```


Running:
1、Server adds: https://127.0.0.1:61681
      Server Display:

  | Remote Address | Protocol | User | Data In | Data Out | Msgs In | Msgs out
  | /127.0.0.1:18092 | any         |         | 0 bytes | 0 bytes    | 0            | 0

2、 The program is not printed   **OnConnected~~~**，  No entry into onConnected；

think you！

**Comment by genii2014** [comment]
Solve

main.cpp
```
int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);
    Publisher pub ;
    //getchar();               **//  Abnormal cause**

    return app.exec();
}
```

Thank you for your help， @mwallnoefer

**Comment by mwallnoefer** [comment]
Okay, `Publisher::Publisher(const QHostAddress &host, const quint16 port, QObject *parent)` seems incomplete in respect to `Publisher::Publisher()`, that means you are not calling `connectToHost()`, you do not set auto reconnect to true and you have less signals connected. But this is certainly not the issue here, since you are using the default parameter-less constructor.

Beside this your code looks correct. I will also have my colleagues have a look at it, maybe they find something suspicious. Other question: do you have tried also with some other broker, also a public one (like mosquitto)? Just to know if the problem could be limited to a specific mqtt broker (I for instance do not know this Apollo Console server)...

@ejvr + @KonstantinRitt Do you see something strange in the code?

**Comment by mwallnoefer** [comment]
Other point which you should check is the protocol version number which the broker Apollo Console supports. We per default use 3.1.0 but optionally support 3.1.1 as well, look at the enumeration in the `qmqtt_client.h` header:

```
enum MQTTVersion
{
    V3_1_0 = 3,
    V3_1_1 = 4
};
```
You may change the version number by calling `setVersion()` before `connectToHost()`.

**Comment by KonstantinRitt** [comment]
-INCLUDEPATH += F:\Downlist\qmqtt-master\src\mqtt
-LIBS += F:/Downlist/build-qmqtt-Desktop_Qt_5_7_0_MinGW_32bit-Debug/lib/libqmqtt.a \
-F:/Downlist/build-qmqtt-Desktop_Qt_5_7_0_MinGW_32bit-Debug/lib/libqmqttd.a
+QT += mqtt

also try connecting *after* the eventloop is running

-clientmqtt->connectToHost();
+QTimer::singleShot(0, clientmqtt, &QMQTT::Client::connectToHost);

**Comment by ejvr** [comment]
Maybe I do not understand the last comment of @genii2014, but my interpretation is that there was a getchar call in the program's main function before starting the event loop. That would explain the problem.

@KonstantinRitt Is there a good reason to connect _after_ starting the event loop? If so, we need to update the QMQTT example (and I need to update some source code as well :) ).

**Comment by KonstantinRitt** [comment]
> Is there a good reason to connect after starting the event loop?

Usually, no. QCoreApplication's event loop collects posted events to process once the event loop started. But here I see some commented-out magic code that makes me think something was expected to be done prior to `exec()`, possibly causing the connection hang by bloating the event loop (or whatever)...

i.e.
getchar() {
QEventLoop el;
el.exec();
}

**Comment by genii2014** [comment]
#148 @Kampfgnom  Analyze the reason correctly

**Comment by mwallnoefer** [comment]
@genii2014 Please follow the advice of KonstantinRitt, looking myself into the `main()` function's code I agree with him that very probably this is a problem of a wrong use of `getchar()`. You would need to find a non-blocking alternative for it or move the mqtt code to another thread (I hope you have some knowledge of thread programming in Qt - there exist some good howtos and hints in the official Qt docs).
