### ISSUE TITLE
qt for android Compiling source code

### ISSUE THREAD

**Issue by genii2014** [emqtt/qmqtt#150]
I have a new question。
Use QT to compile qmtt source code,
Kit : Android for armeabi-v7a(GCC 4.9, Qt 5.7.0)
NDK： r10e
SDK ： android-4.4

Compile error：

cd mqtt\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\android_armv7\bin\qmake.exe F:\Downlist\qmqtt-master\src\mqtt\mqtt.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile install
mingw32-make[1]: Entering directory 'F:/Downlist/qmqtt-master/build-src-Android_for_armeabi_v7a_GCC_4_9_Qt_5_7_0-Debug/mqtt'
**The file name, the directory name, or the volume label syntax is incorrect。**
Makefile:9461: recipe for target 'install_target' failed
**mingw32-make[1]: *** [install_target] Error 1**
mingw32-make[1]: Leaving directory 'F:/Downlist/qmqtt-master/build-src-Android_for_armeabi_v7a_GCC_4_9_Qt_5_7_0-Debug/mqtt'
Makefile:54: recipe for target 'sub-mqtt-install_subtargets' failed
mingw32-make: *** [sub-mqtt-install_subtargets] Error 2
17:08:23: process"D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe"Exit, exit code 2 。
Error while building/deploying project src (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.7.0))
When executing step "Copy application data"

Thank you。

**Comment by mwallnoefer** [comment]
Any chance to have your _Makefile_ posted here (you find it in the build* directory).
Second it would be nice to have the two error messages in Chinese traduced into English.

In general this is strange, as a rule of thumb the build should be working on Android as well.

**Comment by genii2014** [comment]
Add the source code to the project and compile it correctly.

But，Compiling the source code into a dynamic library, error;

**Comment by ejvr** [comment]
Never compiled native code for android, so I can't help you there.

**Comment by KonstantinRitt** [comment]
You're building from QtCreator, it seems. First, check "Build Android APK" build step is disabled. All you really need is `qmake && make install`. If that doesn't help, try updating your Android NDK to something less outdated, i.e. to r14*

**Comment by viettq1991** [comment]
> You're building from QtCreator, it seems. First, check "Build Android APK" build step is disabled. All you really need is `qmake && make install`. If that doesn't help, try updating your Android NDK to something less outdated, i.e. to r14*

It's work, thank you :)
