### ISSUE TITLE
Compiling websocket support

### ISSUE THREAD

**Issue by CoderWannabe** [emqtt/qmqtt#156]
The README.md states that 

> To add websocket support, compile the library with Qt >= 5.7, and specify 'CONFIG += QMQTT_WEBSOCKETS'.

But has I read and tried this is not enough because nowhere the define QT_WEBSOCKETS_LIB is defined. So the parts of code that add the websocket support will not be activated.
Am I right? Is there something that I don't fully understood?

**Comment by ejvr** [comment]
The config setting should cause qmake to set the define. Are you sure you
have qt websockets installed on your system? Including the  development
files?

**Comment by CoderWannabe** [comment]
> The config setting should cause qmake to set the define.


Can you show me where is this trigger? I searched all the qmqtt source for QMQTT_WEBSOCKETS and QT_WEBSOCKETS_LIB, but I didn't see any bond between them.

>Are you sure you have qt websockets installed on your system? Including the development files?


I've QT dynamically linked to my projects on Windows, Linux desktop and Linux embedded. So I haven't the QT source during my building.
I successfully use the qt websocket module in my projects.

**Comment by ejvr** [comment]
Sorry, I misunderstood your question. 

The 'CONFIG += ...' line triggers qmake to enable the module. I don't know what that means in detail, but it will set QMQTT_WEBSOCKETS (and it probably also sets the proper library for linking). You can check this in the makefile generated by qmake (or the MSVC project file).

**Comment by CoderWannabe** [comment]
In the qmqtt.prg there is a conditional that add the websockets module to the QT variable. But I don't get how this can enable the QT_WEBSOCKETS_LIB definition that is used only in this project and not in the qt souce code.

Maybe @mwallnoefer  can help us to understand better.

**Comment by CoderWannabe** [comment]
Ok, finally I get it! Thank you for your patience.

One last think, how do I use this library in my projects?
One way is to compile once the library and then import in any project using the LIBS += and INCLUDEPATH += variables.
But what I see in your code is that you create a new module in qt (mqtt) and maybe the previous isn't the right way to include the library/module in a new project.
In the readme you say to add "QT += qmqtt" to my .pro file, but in a completely new project this module is unknown. So once again in didn't get all your work!

**Comment by ejvr** [comment]
The most common method is to compile and install qmqtt (usually by running `make` and `make install`, I do not know how to do this when you're using visual studio). This will install the qmqtt headers and libraries somewhere inside the QT installation. You may need to run `make install` as root/admin.

After this, you should be able to use QT += qmqtt'

**Comment by CoderWannabe** [comment]
Thank you so much for your explanations. The last two comments set me right.

I owe you one!
