### ISSUE TITLE
PingRequest is sent even when disconnected

### ISSUE THREAD

**Issue by momor10** [emqtt/qmqtt#157]
When trying to connect to a server with autoreconnect set to true, the client will keep trying to reconnect.
After turning autoreconnect off using a checkbox it switches to sending PingRequests and running into timeouts (even though it was never actually connected):

> 
> [2018-09-11-11:18:51.066] Dbg: onMqttError:  1   "SocketConnectionRefusedError"
> [2018-09-11-11:18:53.113] Dbg: onMqttError:  1   "SocketConnectionRefusedError"
> [2018-09-11-11:18:55.151] Dbg: onMqttError:  1   "SocketConnectionRefusedError"
> [2018-09-11-11:18:57.188] Dbg: onMqttError:  1   "SocketConnectionRefusedError"
> [2018-09-11-11:18:59.216] Dbg: onMqttError:  1   "SocketConnectionRefusedError"
> (Checkbox autoreconnect off..)
> [2018-09-11-11:19:09.208] Dbg: onMqttError:  65541   "MqttNoPingResponse"
> [2018-09-11-11:19:19.209] Dbg: onMqttError:  65541   "MqttNoPingResponse"
> [2018-09-11-11:19:29.225] Dbg: onMqttError:  65541   "MqttNoPingResponse"
> [2018-09-11-11:19:39.221] Dbg: onMqttError:  65541   "MqttNoPingResponse"
> [2018-09-11-11:19:49.238] Dbg: onMqttError:  65541   "MqttNoPingResponse"

**Comment by ejvr** [comment]
Yes, it does not make sense to send pings when we know there's no connection.

Give me some time and I'll write a fix.

**Comment by momor10** [comment]
not yet.. the reconnect-mechanism seems to be buggy yet. the reconnect doesnt always work. i couldnt figure it out in more detail yet though.

**Comment by mwallnoefer** [comment]
@ejvr You told us about your intention to deepen this issue. Have you managed to do something?

**Comment by ejvr** [comment]
I totally forgot about that one, due to the fact that I did not work on any qt-related projects for several months.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mwallnoefer** [comment]
Fixed.
