### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by PabloF7** [emqtt/qmqtt#158]
Hi, 
I cannot get qmqtt working. I compiled successfully and i can use it in project. This is the code i'm testing:

```  c++
client = new QMQTT::Client(QHostAddress("test.mosquitto.org"));
client->connectToHost();
client->publish(QMQTT::Message(1,"mynewtopic","message")); 
```
However, i'm getting no "message" in the suscriber, for which i'm using mosquitto client from console.
Any simple example of how to get this working?

Thanks

**Comment by ejvr** [comment]
You have to wait for connection with the broker before you can publish messages.

So you should connect to the `connected` signal, and send the message in the slot connected to the signal.

**Comment by PabloF7** [comment]
Hi,
I've tryied that now, but it never connects. I mean, onConnected slot never gets called.
```c++
MqttClient::MqttClient(QObject *parent) : QObject(parent)
{
    client = new QMQTT::Client(QHostAddress("test.mosquitto.org"));
    connect(client,SIGNAL(connected()),this,SLOT(onConnected()));
    qDebug() << "connecting";
    client->connectToHost();

}

void MqttClient::onConnected(){
    qDebug() << "connected";
    client->publish(QMQTT::Message(1,"mynewtopic","message"));
}

```

**Comment by ejvr** [comment]
You are using a hostname ("test.mosquitto.org") to create a QHostAddress. This is not possible: you can only create a QHostAddress with an IP address. If you want to use a hostname you need another QMQTT::Client constructor.

For example: `new QMQTT::Client("test.mosquitto.org", 1883, false, false)`.

**Comment by PabloF7** [comment]
Thanks a lot! It's working now. I got confused because QHostAdress allowed me to input a string.
