### ISSUE TITLE
auto-reconnect art disconnect

### ISSUE THREAD

**Issue by MyraBaba** [emqtt/qmqtt#161]
is there any such functionality auto-reconnect . ?

**Comment by MyraBaba** [comment]
when I try to re-connect manually server debug says : 

16:12:01.168 [debug] Client(127.0.0.1:56511): Terminated for {shutdown,closed}
16:12:03.168 [debug] Client(127.0.0.1:56513): Terminated for {shutdown,closed}
16:12:05.165 [debug] Client(127.0.0.1:56515): Terminated for {shutdown,closed}
16:12:07.168 [debug] Client(127.0.0.1:56517): Terminated for {shutdown,closed}
16:12:09.164 [debug] Client(127.0.0.1:56519): Terminated for {shutdown,closed}

**Comment by ejvr** [comment]
You can enable auto reconnect using 
`QMQTT::Client::setAutoReconnect(true);`
The reconnect interval is 5 seconds by default. Change it with `setAutoReconnectInterval`.

**Comment by MyraBaba** [comment]
in my qmqtt (from Qt) there is no such option :( 

QMqttClient::setAutoReconnect(true);  is not available

**Comment by ejvr** [comment]
I thinks you're posting to the wrong forum. It seems you are using the mqtt module that comes with QT itself. This is a different library with the same purpose.
