### ISSUE TITLE
connectToHost() fails on Windows10

### ISSUE THREAD

**Issue by ferandec** [emqtt/qmqtt#163]
I have the same problem than those related in issues #148 or #149 : the signal QMQTT::connected() is not fired after calling connectToHost() on Windows 10.
I want to connect to the online broker test.mosquitto.org.
The console program provided with the library (qmqtt_example) works like charm with this broker but when I want to make my own GUI program, it fails due to the fact that the QMQTT:connected signal is not fired.
As suggested in issue #148, I have tried the Qt EMQ GUI Client ([https://github.com/emqtt/qmqtt-client](https://github.com/emqtt/qmqtt-client)) and it fails too.
I then finally tried my program on Linux (Raspberry Pi) and I could see that it was working.

Here is my code (My GUI has a button to connect to the broker and a label updated when connected to the broker) :
### publisher.cpp
```
#include <QDebug>

#include "publisher.h"

Publisher::Publisher()
: QMQTT::Client("test.mosquitto.org", 1883, false, false)
{
    connect(this, &Publisher::connected, this, &Publisher::onConnected);
    connect(this, &Publisher::Client::error, this, &Publisher::onError);
}

void Publisher::onConnected() {
    qDebug() << "Connected to broker";
    subscribe(TOPIC, 0);
}

void Publisher::onDisconnected() {
    qDebug() << "Disconnected from broker";
}

void Publisher::onError() {
    qDebug()  << "MQTT Error";
}
```

### MainIHM.cpp
```
#include "mainihm.h"
#include "ui_mainihm.h"

#include <QDebug>

MainIHM::MainIHM(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::MainIHM)
{
    ui->setupUi(this);

    connect(&mTimer, &QTimer::timeout, this, &MainIHM::onTimeout);
}

MainIHM::~MainIHM()
{
    delete ui;
}

void MainIHM::onTimeout() {
    qDebug() << mPublisher->isConnectedToHost();
}

void MainIHM::onPublisherConnected() {
    ui->lblStatus->setText("Connected !");
}

void MainIHM::on_btnConnect_clicked()
{
    mPublisher = new Publisher();

    connect(mPublisher, &Publisher::connected, this, &MainIHM::onPublisherConnected);

    mPublisher->connectToHost();

    mTimer.setSingleShot(true);
    mTimer.start(2000);
}
```

I wonder what I'm doing wrong or what is the problem with Windows.

any help would be appreciated.

-- ferandec

**Comment by ejvr** [comment]
Just tested the example project on windows, compiled with visual studio 2017 (64bit) and mingw 5.3 (32bit). But work as intended. I have also created a small GUI program based on your code, which also works OK (I could not directly test your code, because the UI definition is missing):

```
#include <QApplication>
#include <QDebug>
#include <QDialog>
#include <QLabel>
#include <QPushButton>
#include <QVBoxLayout>

#include "example.hpp"

class Dialog: public QDialog
{
public:
    Dialog(QWidget *parent=nullptr) :
        QDialog(parent)
    {
        connect(&mTimer, &QTimer::timeout, this, &Dialog::onTimeout);
        auto vbox = new QVBoxLayout;
        setLayout(vbox);
        mStatus = new QLabel("Label", this);
        vbox->addWidget(mStatus);
        auto ok = new QPushButton("OK", this);
        connect(ok, &QPushButton::clicked, this, &Dialog::on_btnConnect_clicked);
        vbox->addWidget(ok);
    }

    void onTimeout()
    {
        qDebug() << mPublisher->isConnectedToHost();
    }

    void onPublisherConnected()
    {
        mStatus->setText("Connected");
    }

    void on_btnConnect_clicked()
    {
        mStatus->setText("Connecting");

        mPublisher = new Publisher();

        connect(mPublisher, &Publisher::connected, this, &Dialog::onPublisherConnected);

        mPublisher->connectToHost();

        mTimer.setSingleShot(true);
        mTimer.start(2000);
    }

private:
    QLabel *mStatus;
    QTimer mTimer;
    Publisher *mPublisher;
};

int main(int argc, char** argv)
{
    QApplication app(argc, argv);
    Subscriber subscriber;
    subscriber.connectToHost();
    Dialog dialog;
    dialog.show();
    return app.exec();
}

```

So you could try to run my code (maybe it works on your system, but I do not know why: my code is doing the same thing as yours). You could also check the firewall on your windows machine. As far as I know, windows will ask the user for permission for each program that tries to create an outbound TCP connection. If the permission has been denied, you will not be able to contact the mqtt server.

By default, a raspberry pi does not have a firewall installed, so that may explain the difference.

If you still have problems, please post which compiler and QT version you are using.

**Comment by ferandec** [comment]
Hello ejvr,

Thank you for your help.

I found the error origin. It was due to the project settings: I've added the libqmqtt library to the project (LIBS += -lqmqtt) in addition to the module qmqtt (QT += qmqtt)...
Then, after deleting the following Qt Creator auto-generated lines in the .pro file after my faulty library addition, the program runs as expected:
```
win32: LIBS += -lqmqtt
win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../../bin/Qt/Qt5.11.2/5.11.2/mingw53_32/lib/ -lqmqtt
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../../bin/Qt/Qt5.11.2/5.11.2/mingw53_32/lib/ -lqmqttd
INCLUDEPATH += $$PWD/../../../../bin/Qt/Qt5.11.2/5.11.2/mingw53_32/include/qmqtt
DEPENDPATH += $$PWD/../../../../bin/Qt/Qt5.11.2/5.11.2/mingw53_32/include/qmqtt
```
I apologize for reporting an issue which wasn't one.

--ferandec
