### ISSUE TITLE
I can't receive the response.

### ISSUE THREAD

**Issue by UsernameKhan** [emqtt/qmqtt#165]
I can publish message to the server. But i can't receive server's message. I don't know why. 
This is my code:
    
    QHostAddress host;
    host.setAddress("my_server_ip");

    client = new QMQTT::Client;
    //client->setClientId("clientId");
    client->setUsername("name");
    client->setPassword("password");
    client->setHost(host);
    client->setPort(1883);
    client->connectToHost();
    
    connect(client, SIGNAL(subscribed(QString,quint8)), this, SLOT(slotSubcribedSuccess(QString)));
    connect(sendButton, SIGNAL(clicked()), this, SLOT(slotSendButton()));
    connect(client, SIGNAL(received(QMQTT::Message)), this, SLOT(slotShowMessage(QMQTT::Message)));

    client->subscribe("MeetingRoom/Room/ResOpen");

**Comment by UsernameKhan** [comment]
Neither slotSubcribedSuccess(QString) nor slotShowMessage(QMQTT::Message) responds. I got crazy.
‘(*>﹏<*)′

**Comment by ejvr** [comment]
You should wait until a connection with the server has been established before subscribing.
So you have to connect to `QMQTT::Client::connected` and call the subscribe function form that slot.

See the example project for more info.

**Comment by UsernameKhan** [comment]
> You should wait until a connection with the server has been established before subscribing.
> So you have to connect to `QMQTT::Client::connected` and call the subscribe function form that slot.
> 
> See the example project for more info.


Thank you very much！I'll try again!

**Comment by UsernameKhan** [comment]
QHostAddress host;
host.setAddress("my_server_ip");

client = new QMQTT::Client;
//client->setClientId("clientId");
client->setUsername("name");
client->setPassword("password");
client->setHost(host);
client->setPort(1883);
client->connectToHost();
//connect(client, SIGNAL(subscribed(QString,quint8)), this, SLOT(slotSubcribedSuccess(QString))); connect(client, SIGNAL(received(QMQTT::Message)), this, SLOT(slotShowMessage(QMQTT::Message)));
connect(sendButton, SIGNAL(clicked()), this, SLOT(slotSendButton()));
connect(client, SIGNAL(connected()), this, SLOT(slotOnConnected()));

**slot：**
void MainWindow::slotOnConnected()
{
    client->subscribe("MeetingRoom/Room/ResOpen");
}

It works！My problem solved~Ensure connected before subscribing~~~
Thanks again~
