### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by KonstantinRitt** [emqtt/qmqtt#167]
I think we're done with this module.
QtMQTT recently got MQTT 5 support and I think we should combine our efforts by contributing to a "standard" Qt module.
Opinions?

**Comment by mwallnoefer** [comment]
@KonstantinRitt + @emqtt/qmqtt-team + @ejvr + others: First of all I share your point of view that it does not make much sense to maintain two independent Qt Mqtt libraries, especially when the former one already got equipped with _Mqtt 5_ support from which we are light years away.

But I guess that there is some little divergence in respect to licensing, in the sense that we have a more liberal model (MIT) than QtMqtt. So I think that we could continue to maintain our code for Mqtt 3.1.1-compatibility, but without adding new features.

**Comment by ejvr** [comment]
I agree. Just leave the project as it is now, and do the necessary maintenance (=bug fixes) only.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by KonstantinRitt** [comment]
I think I'm ok with their less liberate commercial + GPL3 licensing model.

MQTT 3 have no future, IMO.

**Comment by mwallnoefer** [comment]
@emqplus I guess that the right-hand **About** section on https://github.com/emqx/qmqtt should mention the fact that _qmqtt_ has become EOL. There is still people which continues to open new issues not understanding that the project has come to an end.
