### ISSUE TITLE
Using qmqtt under windows

### ISSUE THREAD

**Issue by tipih** [emqtt/qmqtt#17]
Hi I have a hard time using the qmqtt under windows, work fine on MAC and linux, but on windows I get strange linker errors.

I can compile it into a lib, but then when using it I get linker errors.
If I just try to use it in a normale way, I also get errors.

A small number of the errors from the qml-qmqtt project
Makefile.Debug:125: recipe for target 'debug\mqtt.exe' failed
mingw32-make[1]: Leaving directory 'C:/Users/$hschack/Documents/qml-qmqtt'
makefile:34: recipe for target 'debug' failed
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:211: undefined reference to `_imp___ZN5QMQTT6Client12handlePubackEht'
./debug\moc_qmqtt_client.o: In function `ZNK5QMQTT6Client10metaObjectEv':
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:311: undefined reference to `_imp___ZN5QMQTT6Client16staticMetaObjectE'
./debug\moc_qmqtt_client.o: In function `ZN5QMQTT6Client11qt_metacallEN11QMetaObject4CallEiPPv':
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:340: undefined reference to `_imp___ZNK5QMQTT6Client4portEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:341: undefined reference to `_imp___ZNK5QMQTT6Client4hostEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:342: undefined reference to `_imp___ZNK5QMQTT6Client8clientIdEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:343: undefined reference to `_imp___ZNK5QMQTT6Client8usernameEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:344: undefined reference to `_imp___ZNK5QMQTT6Client8passwordEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:345: undefined reference to `_imp___ZN5QMQTT6Client9keepaliveEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:346: undefined reference to `_imp___ZNK5QMQTT6Client13autoReconnectEv'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:353: undefined reference to `_imp___ZN5QMQTT6Client7setPortEj'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:354: undefined reference to `_imp___ZN5QMQTT6Client7setHostERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:355: undefined reference to `_imp___ZN5QMQTT6Client11setClientIdERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:356: undefined reference to `_imp___ZN5QMQTT6Client11setUsernameERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:357: undefined reference to `_imp___ZN5QMQTT6Client11setPasswordERK7QString'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:358: undefined reference to `_imp___ZN5QMQTT6Client12setKeepAliveEi'
C:\Users\$hschack\Documents\qml-qmqtt/debug/moc_qmqtt_client.cpp:359: undefined reference to `_imp___ZN5QMQTT6Client16setAutoReconnectEb'

**Comment by erylee** [comment]
yes, qmtt has the issue on windows, I have no idea still...

**Comment by tipih** [comment]
I think it is releated to the global.h file, and the export import
definitions for libraries, not sure how that could be removed, but I Think
that could be the answer, so insted of using it as a library, just use it
as plain code

Den onsdag den 4. februar 2015 skrev Ery Lee <notifications@github.com>:

> yes, qmtt has the issue on windows, I have no idea still...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emqtt/qmqtt/issues/17#issuecomment-72789201>.
>


-- 
MVH.

.

**Comment by mactro** [comment]
Adding `#define QMQTT_LIBRARY` in global.h fixed a problem for me on Win7 x64.

**Comment by Spitor** [comment]
Hi, i need this library with Windows but I had the same issue. So, still no solutions ?

**Comment by erylee** [comment]
@Spitor, please discuss the issue with @mactro  and @tipih.

**Comment by toni1991** [comment]
Sorry for being impatient, but I heavily rely on running qmqtt on Windows. So is there any improvement?

**Comment by tipih** [comment]
I can Send you à git link

Den tirsdag den 20. oktober 2015 skrev Antonio Grieco <
notifications@github.com>:

> Sorry for being impatient, but I heavily rely on running qmqtt on Windows.
> So is there any improvement?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emqtt/qmqtt/issues/17#issuecomment-149529760>.
>


-- 
MVH.

.

**Comment by toni1991** [comment]
Is there a particular reason to close the issue @wuming123057 ? For me it's still not linkable under Windows :/

**Comment by erylee** [comment]
@toni1991, please discuss the issue with @wuming123057. He said this issue had been fixed:)

**Comment by wuming123057** [comment]
@toni1991 ,tell me the issue please. And,please use new git clone code.

**Comment by wuming123057** [comment]
@toni1991  Is the following issue?
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0x982): undefined reference to `_imp___ZN5QMQTT7MessageC1Ev'
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0x990): undefined reference to `_imp___ZN5QMQTT7Message8setTopicERK7QString'
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0x9b1): undefined reference to `_imp___ZN5QMQTT7Message10setPayloadERK10QByteArray'
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0x9e5): undefined reference to `_imp___ZN5QMQTT7Message6setQosEh'
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0x9ff): undefined reference to `_imp___ZN5QMQTT7MessageD1Ev'
release/qmlqmqtt.o:qmlqmqtt.cpp:(.text+0xa34): undefined reference to `_imp___ZN5QMQTT7MessageD1Ev'

**Comment by toni1991** [comment]
@wuming123057 Sorry was my fault. It's working great! Thank you very much!

**Comment by wuming123057** [comment]
@wguynes
At  new qmqtt library QMQTT::message class redesign  with Q_D point.
You work  great！
And I test it at my windows environment without errors.
This issues can close?

**Comment by wguynes** [comment]
If I have fixed all existing problems with the Windows platform then, yes, this issue should be closed.

**Comment by Pavlines** [comment]
Please give me a library for windows

**Comment by mwallnoefer** [comment]
We do not provide any binary distributions. The build works also on Windows, just add the `NO_UNIT_TESTS` to the qmake `CONFIG` flags (e.g. `CONFIG += NO_UNIT_TESTS`). If you encounter other errors, please report them here!

**Comment by Pavlines** [comment]
I still can not compile this. Not under Windows, nor under Linux. Always produces an error when compiling. In particular, the absence of the qmqtt.h file . How can I get a library file or a header file, so just connect it to my project.
I work in Qt, under Windows

**Comment by mwallnoefer** [comment]
@Pavlines Hard to say. Do you have a chance to attach us a full build log? I am always building it in Qt Creator and there it works like a charm.

@emqtt/qmqtt-team Has anyone an idea what this could be (absence of _qmqtt.h_)?

**Comment by Pavlines** [comment]
Programm C:\Users\Pavlines\Desktop\build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release\examples\mqtt\client\release\qmqtt_example.exe absent.

**Comment by Pavlines** [comment]
![image](https://cloud.githubusercontent.com/assets/26151153/25779778/c5c4d8b4-3326-11e7-8360-c46190bd2771.png)

**Comment by Pavlines** [comment]
![image](https://cloud.githubusercontent.com/assets/26151153/25779786/defe9284-3326-11e7-8a30-324e30fd5b5c.png)

**Comment by Pavlines** [comment]
13:10:03: Выполняются этапы для проекта qmqtt...
13:10:03: Настройки не изменились, этап qmake пропускается.
13:10:03: Запускается: «C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe» 
cd src\ && ( if not exist Makefile C:\Qt\5.9\mingw53_32\bin\qmake.exe -o Makefile C:\Users\Pavlines\Desktop\qmqtt-master\src\src.pro -spec win32-g++ ) && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src'
cd mqtt\ && ( if not exist Makefile C:\Qt\5.9\mingw53_32\bin\qmake.exe -o Makefile C:\Users\Pavlines\Desktop\qmqtt-master\src\mqtt\mqtt.pro -spec win32-g++ ) && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[2]: Entering directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Release all
mingw32-make[3]: Entering directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
mingw32-make[3]: Nothing to be done for 'all'.
mingw32-make[3]: Leaving directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug all
mingw32-make[3]: Entering directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
mingw32-make[3]: Nothing to be done for 'all'.
mingw32-make[3]: Leaving directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
mingw32-make[2]: Leaving directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src/mqtt'
mingw32-make[1]: Leaving directory 'C:/Users/Pavlines/Desktop/build-qmqtt-Desktop_Qt_5_9_0_MinGW_32bit-Release/src'
13:10:06: Процесс «C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe» завершился успешно.
13:10:06: Прошло времени: 00:02.

**Comment by mwallnoefer** [comment]
Aha, this is Qt 5.9 with MinGW 32 on Windows. For sure you have already tried to clean up and rebuild from scratch? And in your log I do not see the error message about the missing `qmqtt.h`?

Personally I use Qt 5.6 where the build works without issues.
@emqtt/qmqtt-team Has anyone tested Qt 5.9?

**Comment by Pavlines** [comment]
The project is compiled. But nothing is created except the lib-file.  Also does not create  qmqtt.h in relise folder.  I'm trying to compile a emqtt/qmqtt-client project. But I do not know how to force it to compile a  emqtt/emqtt project into a library with an "qmqtt.h" file. To connect it to the emqtt/qmqtt-client project.

**Comment by mwallnoefer** [comment]
I have seen only now that this is a known issue #89 (I didn't remember), so please let us follow-up it there. As a workaround you could try building it with Qt 5.6 or 5.7 where it works.

**Comment by pavanic002** [comment]
![mqtterr](https://user-images.githubusercontent.com/20797539/28821528-63dfb3da-76d3-11e7-9e94-99166a2230a9.png)

Hi,
   I'm facing issue with Makefile while building qmqtt in windows. I'm using Qt 5.6.0 (MSVC 2013, 32 bit). 
Please refer console output below.

15:39:08: Running steps for project qmqtt...
15:39:08: Starting: "C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe" clean
	cd src\ && ( if not exist Makefile C:\Qt(32)\Qt5.6.0\5.6\msvc2013\bin\qmake.exe "C:\Users\pavani_Chadalapaka\Downloads\qmqtt-master (2)\qmqtt-master\src\src.pro" -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe -f Makefile clean
\Qt5.6.0\5.6\msvc2013\bin\qmake.exe was unexpected at this time.
jom: C:\Users\pavani_Chadalapaka\Downloads\qmqtt-master (2)\build-qmqtt-Desktop_Qt_5_6_0_MSVC2013_32bit-Debug\Makefile [sub-src-clean] Error 1
15:39:08: The process "C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
15:39:08: Configuration unchanged, skipping qmake step.
15:39:08: Starting: "C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe" 
	cd src\ && ( if not exist Makefile C:\Qt(32)\Qt5.6.0\5.6\msvc2013\bin\qmake.exe "C:\Users\pavani_Chadalapaka\Downloads\qmqtt-master (2)\qmqtt-master\src\src.pro" -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe -f Makefile
\Qt5.6.0\5.6\msvc2013\bin\qmake.exe was unexpected at this time.
jom: C:\Users\pavani_Chadalapaka\Downloads\qmqtt-master (2)\build-qmqtt-Desktop_Qt_5_6_0_MSVC2013_32bit-Debug\Makefile [sub-src-make_first] Error 1
15:39:09: The process "C:\Qt(32)\Qt5.6.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project qmqtt (kit: Desktop Qt 5.6.0 MSVC2013 32bit)
When executing step "Make"
15:39:09: Elapsed time: 00:01.

**Comment by mwallnoefer** [comment]
That's odd. I under Qt 5.6 with MSVC2013 32 bit get this if I am doing a qmake:

14:54:08: Running steps for project qmqtt...
14:54:08: Starting: "C:\Qt\5.6\msvc2013\bin\qmake.exe" C:\Users\MatthiasW\Git\qmqtt\qmqtt.pro -spec win32-msvc2013
14:54:08: The process "C:\Qt\5.6\msvc2013\bin\qmake.exe" exited normally.
14:54:08: Starting: "C:\Qt\Tools\QtCreator\bin\jom.exe" qmake_all

jom 1.1.2 - empower your cores

	cd src\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\src\src.pro -spec win32-msvc2013 -o Makefile
	cd src\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd mqtt\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\src\mqtt\mqtt.pro -spec win32-msvc2013 -o Makefile
<srcbase> = c:/Users/MatthiasW/Git/qmqtt 
<outbase> = c:/Users/MatthiasW/Git/build-qmqtt-Desktop_Qt_5_6_2_MSVC2013_32bit-Release 
Project MESSAGE: perl -w C:\Qt\5.6\msvc2013\bin\syncqt.pl -module qmqtt -version 1.0.0 -outdir C:/Users/MatthiasW/Git/build-qmqtt-Desktop_Qt_5_6_2_MSVC2013_32bit-Release C:/Users/MatthiasW/Git/qmqtt
	cd mqtt\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd examples\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\examples\examples.pro -spec win32-msvc2013 -o Makefile
	cd tests\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\tests\tests.pro -spec win32-msvc2013 -o Makefile
	cd examples\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd mqtt\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\examples\mqtt\mqtt.pro -spec win32-msvc2013 -o Makefile
	cd mqtt\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd client\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\examples\mqtt\client\client.pro -spec win32-msvc2013 -o Makefile
	cd tests\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd auto\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\tests\auto\auto.pro -spec win32-msvc2013 -o Makefile
	cd auto\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd cmake\ && C:\Qt\5.6\msvc2013\bin\qmake.exe C:\Users\MatthiasW\Git\qmqtt\tests\auto\cmake\cmake.pro -spec win32-msvc2013 -o Makefile
	cd cmake\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
	cd client\ && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
14:54:10: The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited normally.
14:54:10: Elapsed time: 00:02.

**Comment by nizqsut** [comment]
Still have issue on Windows 10 64bit / Based on Qt 5.11.1.
":-1: error: [sub-mqtt-qmqtt-pro-qmake_all] Error 3."

**Comment by nizqsut** [comment]
Fixed it. It need to install perl for windows.
