### ISSUE TITLE
error: expected primary-expression before '[' token

### ISSUE THREAD

**Issue by singoo** [emqtt/qmqtt#170]
I have a "error: expected primary-expression before '[' token" in qmqtt_router.cpp.
I am a newbie who doesn't know how to solve this problem.
Please help me.

**Comment by singoo** [comment]
Base on Qt 5.5.1, and kit is Desktop qt 5.5.1 GCC 32bit

**Comment by mwallnoefer** [comment]
Could it be that you are using a MinGW gcc version which is not yet C++11 enabled?

@KonstantinRitt + @ejvr : What do you think?

**Comment by ejvr** [comment]
That seems like the most logical explanation. Is this a compiler error in line 52 of qmqtt_router.cpp?

Is so, this file is not part of the core QMQTT module, so you could compile the module without qmqtt_router and qmqtt_routedsubscription.
As far as I know, core QMQTT does not use any c++-11 (or later) features.

This may not be related, but you should also realize then QMQTT only works with QT version 5.3 or higher.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by singoo** [comment]
Thank you for your help.

> Could it be that you are using a MinGW gcc version which is not yet C++11 enabled?
> 
> @KonstantinRitt + @ejvr : What do you think?
