### ISSUE TITLE
Ssl compilation failed.

### ISSUE THREAD

**Issue by singoo** [emqtt/qmqtt#173]
My OS is CentOS release 6.8(Final). Qt version is 5.5.3. 
I find a problem that QSslSocket can't pass compilation. 
Finally found that the problem is in the pre-compilation.
Unable to find precompiled QT_NO_SSL in qmqtt_ssl_socket.
Compile successfully when #ifndef is changed to #ifdef.
But I don't know why.
So,please give me help.
Thank you very much.

**Comment by mwallnoefer** [comment]
@ejvr I think you are the expert here.

**Comment by ejvr** [comment]
I just compiled the latest version of QMQTT with and without ssl support. Both are OK. Also, I can't find any problem in the source code.

Can you post the compiler output including the error message? Maybe that will help.

**Comment by singoo** [comment]
error: invalid use of incomplete type 'class QSslSocket'
./qmqtt/src/mqtt/qmqtt_ssl_socket_p.h:46: error: forward declaration of 'class QSslSocket'
![image](https://user-images.githubusercontent.com/29615989/56400472-a2eb9a80-6286-11e9-9c64-61081930f229.png)

**Comment by ejvr** [comment]
Thanks, apparently something is wrong with the forward declaration of QSslSocket in qmqtt_ssl_socket_p.h (or there is some mess up with QT_USE_NAMESPACE). 

I'm not sure this will fix the problem, but can you try to replace `QT_FORWARD_DECLARE_CLASS(QSslSocket)` with `#include <QSslSocket>` in `src/mqtt/qmqtt_ssl_socket_p.h`?

**Comment by singoo** [comment]
I should thank you more because you are helping me solve problems that I can't solve.
I did what you said.But did not solve the problem.
Please see the two pictures below.
I am wondering exactly where the macro definition is not in effect.
I am also confused.

![image](https://user-images.githubusercontent.com/29615989/56418060-6e98ce00-62c8-11e9-86c7-afdec22b8435.png)
![image](https://user-images.githubusercontent.com/29615989/56418110-90925080-62c8-11e9-9020-04b9afd56626.png)

**Comment by singoo** [comment]
Sorry. This is the result of the revision according to your instructions.

![image](https://user-images.githubusercontent.com/29615989/56418495-a5231880-62c9-11e9-80c0-9081ca1576f3.png)

**Comment by ejvr** [comment]
This is very strange. It seems that when compiling the value of `QT_NO_SSL` somehow changes. That should not be possible. Can you try to compile qmqtt on the command line? That would exclude problems with QT creator.

So in a shell go to the qmqtt directory and run
`mkdir build`
`cd build`
`qmake ..`
`make`
`make install`

(if you get an error when running qmake you probably need to use the full path the the executable)

Does that work? If not, can you send us the full output?

**Comment by mwallnoefer** [comment]
Any news here, otherwise we mark it as resolved?

**Comment by singoo** [comment]
Yep, I'll solve by myself.
Thanks everybody.
