### ISSUE TITLE
Example publisher Websocket ?

### ISSUE THREAD

**Issue by audicm2** [emqtt/qmqtt#176]
Hi,

I try to make a client publisher websocket but i have a little trouble... it's possible to find a example for websocket ? Or help me ?

```
#ifndef PUBLISHERWEB_H
#define PUBLISHERWEB_H

#include <qmqtt.h>
#include <QCoreApplication>
#include <QTimer>
#include <iostream>

const QString EXAMPLE_URL = "broker.mqttdashboard.com";// Or QHostAdress()
const quint16 EXAMPLE_PORT = 8000;
const QString EXAMPLE_ORIGIN = "broker.mqttdashboard.com";
const QString EXAMPLE_TOPIC = "test";





class Publisher : public QMQTT::Client
{
    Q_OBJECT
public:
    explicit Publisher(const QString& url = EXAMPLE_URL,
                       const QString& origin = EXAMPLE_ORIGIN,
                       QWebSocketProtocol::Version version, // error : QwebSocketProtocol is not declared ??
                       bool ignoreSelfSigned = false,
                       QObject* parent = NULL)
        : QMQTT::Client(url, origin, version, NULL, ignoreSelfSigned)
        , _sentence("Hello")


    {
        connect(this, &Publisher::connected, this, &Publisher::onConnected);
        connect(&_timer, &QTimer::timeout, this, &Publisher::onTimeout);
        connect(this, &Publisher::disconnected, this, &Publisher::onDisconnected);
    }
    virtual ~Publisher() {}

    QTimer _timer;
    //quint16 _number;
    QString _sentence;

public slots:
    void onConnected()
    {
        subscribe(EXAMPLE_TOPIC, 0);
        _timer.start(1000);


    }

    void onTimeout()
    {
        QMQTT::Message message(1, EXAMPLE_TOPIC,
                               QString("This is my sentence :").arg(_sentence).toUtf8());
        publish(message);

    }

    void onDisconnected()
    {
        QTimer::singleShot(0, qApp, &QCoreApplication::quit);



    }
};

#endif // PUBLISHERWEB_H
```

And it's impossible to include the WebSocket Lib, it's grayed out..

see here : [http://zupimages.net/viewer.php?id=19/17/07pd.png]

thanks for your answer !

**Comment by audicm2** [comment]
And it's impossible to include the WebSocket Lib, it's grayed out..

**Comment by mwallnoefer** [comment]
I think this lies in the domain of @KonstantinRitt which contributed the WebSockets support...

**Comment by KonstantinRitt** [comment]
Nope, that wasn't me)

One have to build qmqtt with websockets enabled, then also add
> QT += websockets
to the client's qmake project

see https://doc.qt.io/qt-5/qtwebsockets-examples.html for more examples

**Comment by mwallnoefer** [comment]
Ah sorry, it was @ejvr :).

**Comment by audicm2** [comment]
Hi,

I have add 

```
QT += qmqtt
QT += websokets

CONFIG += QMQTT_WEBSOCKETS
```

but 

```
#ifdef QT_WEBSOCKETS_LIB

....

#endif // QT_WEBSOCKETS_LIB 
```

is always grayed out.

except if it's not QT_WEBSOCKETS_LIB with mqtt but qtwebsockets with qt ?

Thanks for your answer.

**Comment by audicm2** [comment]
The same, in qmqtt project, qmqtt_websocket.cpp and qmqtt_websocketiodevice.cpp is grayed out

**Comment by ejvr** [comment]
Can you try to create a fresh clone of qmqtt and run this:
`qmake CONFIG+=QMQTT_WEBSOCKETS ..`
Note: no spaces around '+='. 

That's how qmqtt is intended to be build. This will compile the qmqtt module and the example. You can modify the client example to use the QMQTT::Client constructor for websockets.
