### ISSUE TITLE
unresolved symbol in message router

### ISSUE THREAD

**Issue by maggu2810** [emqtt/qmqtt#20]
I am using Qt 5.4.1 at the moment.

You are using "QLoggingCategory" (https://github.com/emqtt/qmqtt/blob/4406d6f6b5352dcc796970c65da0d6e7e963e1cd/qmqtt_client_p.h#L40). This class was introduced in Qt 5.2 (http://doc.qt.io/qt-5/qloggingcategory.html), so I am using Qt5, not Qt4.

If I add a main to the current source code and compile it as an application, I get an error about unresolved symbols.

The error complains missing "routeMessage" a slot defined for RouteSubscription.
https://github.com/emqtt/qmqtt/commit/b9ef8e4ef6f8c549c391b0215f3ca41632ac6c74#diff-8fd9f2b86c31347db2c08db95731b25dR69

I have a look at the moc output and it seems that only the first class containing Q_OBJECT is evaluated.

I never mixed multiple classes that use the qt meta system in one header file.
Is this common practice now?

**Comment by erylee** [comment]
@maggu2810 RouteSubscription is a feature contributed by @Kampfgnom for I was coding Erlang these years and did not maintain this project:)

@Kampfgnom, would you like to check this issue? Thanks.

**Comment by Kampfgnom** [comment]
I will check it out.

**Comment by Kampfgnom** [comment]
@maggu2810 Which compiler and system are you using?

**Comment by maggu2810** [comment]
I think the error is in the project settings.
The sources points to the header file, not to the source.
https://github.com/emqtt/qmqtt/blob/master/qmqtt.pro#L21
So the whole qmtt_router implementation is missing.

**Comment by Kampfgnom** [comment]
Okay. That's just wrong. Thats my fault... I use the pri file, which is why I didn't notice the error, sorry.

**Comment by maggu2810** [comment]
No problem at all.

**Comment by Kampfgnom** [comment]
And BTW: I often have several classes per header when the resulting cpp file stays small enough. I never had any problems with that under any system (using debian, ubuntu, OSX 10.9/10.10, windows with mingw 4.9 and msvc 2013)

**Comment by maggu2810** [comment]
I do this for simple stuff, but I do not use this as well as it is possible for me.
It is more about design philosophy and out of scope of this issue. ;-)
