### ISSUE TITLE
Add "INSTALLS" to project-file

### ISSUE THREAD

**Issue by Psy-Kai** [emqtt/qmqtt#27]
Hello,

could you please add an INSTALLS to the project file with an prefix?

    isEmpty(PREFIX) {
        contains(MEEGO_EDITION,harmattan) {
            PREFIX = /usr
        } else:unix {
            PREFIX = /usr/local
        } else {
            PREFIX = $$[QT_INSTALL_PREFIX]
        }
    }
    
    headers.files = $$HEADERS
    headers.path = $$PREFIX/include/qmqtt
    target.path = $$PREFIX/lib
    INSTALLS += headers target

This would simplify the installation alot.

**Comment by erylee** [comment]
@Psy-Kai, could you fork the project and submit a PR? Thanks.
