### ISSUE TITLE
Qt Library Dependency

### ISSUE THREAD

**Issue by ve7mjc** [emqtt/qmqtt#30]
It would appear that due to QRegularExpressions and QLoggingCategory, this can only be compiled in >= Qt 5.2?  I tried to comment out all of the QLoggingCategory calls, which works but then got nailed by the QRegularExpressions libraries vice QRegExp.

a) Is there a previous revision which operates under Qt 4.x ? (thinking for Raspberry Pi and the mainstream embedded stuff here)

b) could someone throw a note on the main readme to prevent others from similar pain

I have this client library compiled and running great in a Windows VM - I certainly appreciate the devs writing it!

**Comment by wuming123057** [comment]
I'm sorry, so long to reply to you.

a)there isn't a previous revision which operates under Qt 4.x .
b)ok. I throw a note on the main readme right now.
This library was written in the >=Qt 5.2 version by the author not me.
And Qt5 was stable until the >=Qt 5.2 version.
This year,Qt5 update is very fast with a lot of changes, not as stable as Qt4.

**Comment by wguynes** [comment]
As I am about to start stabilizing and adding features, I can assume that we're going to stay consistent with Qt5 API? If we plan on back porting to Qt4 I should probably abstract a few things.

**Comment by wuming123057** [comment]
@wguynes 
Qt 5.6 will be a long-term supported release as we announced at the Qt World Summit in the beginning of October. This means Qt 5.6 support for 3 years along with additional patch-level releases.
So, the library based on Qt5 is a very good choice.

**Comment by ve7mjc** [comment]
Qt5 is now present in the Debian Jessie main distributions and thus easily attained on the Raspberry Pi and other similar platforms. I would not request that effort be placed in back-porting to Qt 4.

Thank you for adding the note regarding the target Qt version.  We will undoubtedly save others some time.

**Comment by george-hopkins** [comment]
Just a small note for further reference (and a bit of shameless promotion :wink:): A backport to Qt 4 is now available: https://github.com/george-hopkins/qmqtt-qt4

**Comment by mwallnoefer** [comment]
I think this may be closed, we have added a note to the **README** stating that qmqtt works only with Qt >= 5.3.

@george-hopkins Regarding the Qt4 back-port: please keep up with merging our fixes and improvements, otherwise users end up in old bugs!

**Comment by george-hopkins** [comment]
@mwallnoefer Thank you reminding me! I just merged all changes back in to the backport. Now SSL and all the bugfixes are available for Qt 4 as well.

Just ping me again in case I fall behind too much. I will try to keep up faster in the future.

**Comment by mwallnoefer** [comment]
Please have a look now, I have merged some other bug fix (69fd712896176d376e50cf6db5b605fe92c04133).
