### ISSUE TITLE
Major, hopefully final public interface break

### ISSUE THREAD

**Issue by wguynes** [emqtt/qmqtt#35]
My [upcoming] changeset is going to make the public interface more solid.

* Full PIMPL pattern for the public API for ABI compatibility.
* Renaming a few functions, `QMQTT::Client::connect()` is a dangerous override and is going to cause user (developer) confusion. I am proposing change it to `QMQTT::Client::connectToHost()` which follows a Qt standard set by `QTcpSocket`
* Isolation of header files. The user should only need `qmqtt_client.h` to compile and link with this library.

Once these changes are in, we will stop breaking source and binary compatibility as we enhance the library.

I do have some problems that need solutions:
* Does anyone know the standard for eliminating the  `qmqtt_client.h` dependence on `qmqtt_global.h` ? I know the global.h pattern is standard but what do we do once it is time to package it?
* Are we really attached to the `QMQTT::Will` class? If the user must pass in an instance of this class then I have to expose the header file to them. I don't like that.

**Comment by wuming123057** [comment]
You can refer to http://wiki.qt.io/Dpointer .
If we  stop breaking source and binary compatibility ,the library must be rewritten.
it will be more easy to use,  if we rewritten the library to  take more time.
