### ISSUE TITLE
Resending messages when QoS > 0 seems to be unimplemented

### ISSUE THREAD

**Issue by mvirkkunen** [emqtt/qmqtt#39]
I couldn't find any code that would store messages and retransmit them if QoS > 0 and the server does not send a PUBACK - is this unimplemented or am I just not finding the relevant code?

It might be good to remove the QoS parameters if they're not actually supported so users don't get the wrong idea.

**Comment by wguynes** [comment]
It is true that this functionality was not yet implemented. I have so far
been trying to refactor and get tests around the functionality that already
existed.

I'm going to start adding new behavior in the next round of changes.

**Comment by mwallnoefer** [comment]
Also here commit 83ad60daee086b0fdf5012a10060a195ea062338 improved qmqtt's functionality in the sense that a proper signal gets raised `published(const quint16 msgid, const quint8 qos)`, when a message has been acknowledged by the broker.

@mvirkkunen If this is not enough and you prefer to have the internal queue, please reopen!
