### ISSUE TITLE
autoReconnect doesn't do anything

### ISSUE THREAD

**Issue by mvirkkunen** [emqtt/qmqtt#40]
As far as I can tell this property exists in the public interface but it's never used for anything. It's not documented in the README but it's been there for a year - is this unfinished?

**Comment by wguynes** [comment]
Correct. As far as I can tell it was not yet implemented.

**Comment by wuming123057** [comment]
Sorry.We'll do it as soon as possible.

**Comment by wguynes** [comment]
Do we wish to let the developer set the retry interval?
I made it 5 seconds for now.

**Comment by mvirkkunen** [comment]
It might be a good idea to make it configurable. Many clients also support "exponential backoff" but letting the retry interval grow too big might not be a good idea for IoT style things. It would make it unresponsive.

(And @wuming123057, heh, there's no need to be sorry. I was just pointing out that the setting doesn't do anything yet in case somebody wonders.)

**Comment by wguynes** [comment]
Should I use the same value for a "failed connect" condition?
As opposed the current "lost connection" condition.

**Comment by mvirkkunen** [comment]
I've seen some clients behave differently if the initial connection fails, even give up altogether because it might signify a configuration error. But I think it's important to at least be able to specify that reconnection should still happen even if the initial connection fails, in case the remote server was temporarily down at the very moment the client was started.

Not sure if there's a need to specify different time delays for both though.

**Comment by wguynes** [comment]
Okay, for now "autoreconnect" applies to both connection_fail and connection_lost. I'm on that now.

**Comment by mvirkkunen** [comment]
...of course I'm not an expert authority on network clients, but from a user's perspective I think these days with unreliable mobile connections and all you usually want a robust reconnection feature that "just works" without having to think about it.

**Comment by wguynes** [comment]
Agreed. It should do something sensible out of the box.

**Comment by wguynes** [comment]
Configurable autoreconnect now done.
User can turn it on an off (default: off)
User can set the retry interval in ms (default: 5000)
