### ISSUE TITLE
Ping timeouts are not detected

### ISSUE THREAD

**Issue by mvirkkunen** [emqtt/qmqtt#41]
PINREQs seem to be sent correctly, but for reliability's sake it would be good to raise a connection error if a PINGRESP isn't received in response to a PINGREQ.

**Comment by wguynes** [comment]
My next task is to start writing tests to start complying with the [3.1.1 specification]
(http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html).

**Comment by wuming123057** [comment]
@wguynes 

The master repo of [qmqtt-client](https://github.com/emqtt/qmqtt-client/tree/master) corresponds to the new qmqtt library.
Please you  download the test.
And you will add ack and errors ?

**Comment by wguynes** [comment]
Correct PINGRESP behavior will first require a proper state machine. I will implement it.

**Comment by mwallnoefer** [comment]
@wguynes Any news here?

**Comment by mwallnoefer** [comment]
83ad60daee086b0fdf5012a10060a195ea062338 has improved the situation in the sense that it added some `pingresp()` signal, so closing for now.
