### ISSUE TITLE
Problem compiling qmqtt in Windows

### ISSUE THREAD

**Issue by krimp** [emqtt/qmqtt#42]
I am trying to compile the qmqtt subproject in Win7 using QtCreator 3.6.0 with MSVC SDK 7.1 (Qt 5.5.1).

The compilation stops in qmqtt_frame.cpp

64  Frame& Frame::Frame::operator=(const Frame& other)
65  {
66    _header = other._header;
67    _data = other._data;
68   return *this;
69 }

with the following errors:

C:\Qt\qmqtt-master\qmqtt-master\src\qmqtt_frame.cpp:64: error: C3083: '{ctor}': the symbol to the left of a '::' must be a type
C:\Qt\qmqtt-master\qmqtt-master\src\qmqtt_frame.cpp:65: error: C2556: 'QMQTT::Frame::Frame(const QMQTT::Frame &)' : overloaded function differs only by return type from 'QMQTT::Frame &QMQTT::Frame::operator =(const QMQTT::Frame &)'
c:\qt\qmqtt-master\qmqtt-master\src\qmqtt_frame.h:95: see declaration of 'QMQTT::Frame::operator ='

In the qmqtt_frame.h the deifnition is
Frame& operator=(const Frame& other);

Does anybody know what to do?

**Comment by wguynes** [comment]
That appears to be my fault. There should not be two Frame:: scopes on line 64.
I will fix it when I get home.

The line should read

    64:Frame& Frame::operator=(const Frame& other)
