### ISSUE TITLE
MQTT 3.1.1 support

### ISSUE THREAD

**Issue by yupengfei** [emqtt/qmqtt#60]
Does this library support mqtt 3.1.1 yet? Or do you have a plan?

**Comment by mwallnoefer** [comment]
Looking here I guess that it is already 3.1.1: https://github.com/emqtt/qmqtt/blob/master/src/qmqtt_client.h

Do you miss some particular feature?

**Comment by yupengfei** [comment]
Sorry I did not read your code carefully.

**Comment by yupengfei** [comment]
@mwallnoefer https://github.com/emqtt/qmqtt/blob/master/src/qmqtt_frame.h The PROTOCOL_MAGIC "MQIsdp" say it is still MQTT 3.1.
