### ISSUE TITLE
Porting qmqtt to Android

### ISSUE THREAD

**Issue by ftheirs** [emqtt/qmqtt#68]
Hi guys!
has anyone tried to port this mqtt client to android? I can run it in Desktop without problems but I have some issue with: library "libqmqtt.so" not found. Since I'm new in QT and Android I don't really have idea what the problem is. Could someone help me?

Thanks,
Fernando

**Comment by wuming123057** [comment]
It's not tested yet.But I recommend using eclipse.paho. And Qt  call this library  on Android.
http://www.eclipse.org/paho/clients/android/sample/

**Comment by mwallnoefer** [comment]
It works fine, you have only to bundle it with your application like this:

```
else:unix:android: {
contains(ANDROID_TARGET_ARCH,armeabi-v7a) {
    LIBS += -lqmqtt -L$$QMQTT_BUILD_PATH_ANDROID_ARMV7A/src/
    ANDROID_EXTRA_LIBS += $$QMQTT_BUILD_PATH_ANDROID_ARMV7A/src/libqmqtt.so
}
contains(ANDROID_TARGET_ARCH,x86) {
    LIBS += -lqmqtt -L$$QMQTT_BUILD_PATH_ANDROID_X86/src/
    ANDROID_EXTRA_LIBS += $$QMQTT_BUILD_PATH_ANDROID_X86/src/libqmqtt.so
}
}
```

The variables point to a location where you had compiled the library for Android:
```
QMQTT_BUILD_PATH_ANDROID_ARMV7A = H:/Qt/build-qmqtt-Android_for_armeabi_v7a_GCC_4_9_Qt_5_6_0-Release
QMQTT_BUILD_PATH_ANDROID_X86 = H:/Qt/build-qmqtt-Android_for_x86_GCC_4_9_Qt_5_6_0-Release
```

**Comment by ftheirs** [comment]
Hi @wuming123057  thanks for the advice! I'll read about it!! And @mwallnoefer : yes! the problem was that some path was missing. I'm new in Qt and I haven't written in C++ for 5 years so.. I'm a little bit rusty. The library is created well and I have others problems but my concern was the library.
Many thanks to both of you, the problem was solved :)
