### ISSUE TITLE
Messages are not sent when compiling with Qt 5.7 on ARM

### ISSUE THREAD

**Issue by qgicup** [emqtt/qmqtt#74]
It seems that the client is connecting, it pushes the messages (says successfully sent), however, we cant get them on another MQTT client.
Strangely, when we compile with Qt 5.2, we do receive the messages.
Can provide full log if needed.

**Comment by ejvr** [comment]
As far as I understand the MQTT protocol, you are not allowed to publish (or subscribe) to a broker before you have connected and received an acknowledgement from the broker (CONNACK).

Using qmqtt this means you should not publish or subscribe before the Client::connected signal is emitted. If you start sending before you have a race condition between your application and the broker. You may be able to spot this in the logs: the broker should send the CONNACK (this is the first packet sent by the broker after connection has opened), before it receives the publish request from your application.

Additionally you may try a little modification in the qmqtt code. In the ClientPrivate class the connected signal is emitted in the onNetworkConnected function (which is called when the TCP connection has been opened), and move it to the handleConnack function (called after the CONNACK has been received from the broker).

**Comment by qgicup** [comment]
Yes, I've just made those changes to the client + acknowledgements for subscribe/publish/unsubscribe, and I think I will launch a pull request with them, so others can benefit from them as well.
Thanks for help @ejvr !
