### ISSUE TITLE
Auto Reconnect Timeout is always 5 sec.

### ISSUE THREAD

**Issue by gmgkostik** [emqtt/qmqtt#84]

**Comment by ejvr** [comment]
You're right. The timeout of the auto reconnect timer is set during initialization, and will not be changed later.
You could try to add `_autoReconnectTimer->setInterval(_autoReconnectInterval);` to `QMQTT::Network::setAutoReconnectInterval`, that should fix it.

**Comment by mwallnoefer** [comment]
Should be fixed with this commit.
