### ISSUE TITLE
Building under Windows

### ISSUE THREAD

**Issue by titan83** [emqtt/qmqtt#85]
Hello, sorry, I understand that my question is more in Qt sphere...
But I should to use qmqtt under windows and it's a pain for me.
Win7 x64, Qt5.7.1 with MinGW 5.3.
When I open qmqtt.pro I have next General messages:
```
Project WARNING: You should probably load(qt_build_config) first in mqtt.pro for qmqtt, as the latter also load()s qt_module.  
Project MESSAGE: Not doing so may lead to qt_module.prf overriding compiler/linker options in your .pro file.  
Project MESSAGE: Ignore this warning with CONFIG+=no_qt_module_warning if you know what you are doing.  
Project ERROR: Module does not define version. Error while parsing file C:\Users\user\Documents\qmqtt\src\mqtt\mqtt.pro. Giving up.  
[Inexact] Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.  
[Inexact] Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.  
[Inexact] Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!  
Project MESSAGE: perl -w C:\Qt\Qt5.7.1\5.7\mingw53_32\bin\syncqt.pl -module qmqtt -version 1.0.0 -outdir C:/Users/user/Documents/build-qmqtt-Desktop_Qt_5_7_1_MinGW_32bit-Debug C:/Users/user/Documents/qmqtt  
```
I installed Perl anc CMake (thay are in PATH and works), because in first time it were a bit more messages)
But I can build it. I move manually includes and cmake file into Qt directories, but if I want to build example client application I have a message: error: Unknown module(s) in QT: mqtt
I understand that qmqtt folder looks like qt module, but I have a bit mess how to install it.
So, maybe you throw me a some ideas how to fix it.

Great thanks for your project!

**Comment by titan83** [comment]
Ok.
I answer on my question
my problem was in next: perl failed, if your project placed into long directory name, like a "C:\Documents ans settings\etc\bla", so put it into something simple, like "C:\qmqtt".
Also you need a make-analogue utilite under windows, I used mingw32-make.
Also add to PATH make dir, perl (ActivePerl, for example) dir, qmake dir.
Finally:
1. dir c:\qmqtt
2. qmake
3. mingw32-make
4. mingw32-make install
That's all.

Sorry, it was a spam, but I hope it will help to some noob with Qt under windows (like me).

Good bye.

**Comment by mwallnoefer** [comment]
Okay, so I guess we can mark it closed though.
