### ISSUE TITLE
Qmqtt Android Build in Linux 

### ISSUE THREAD

**Issue by fuxey** [emqtt/qmqtt#94]
Hi guys,

i try to compile the sources for android armv7 with qt5.8 in linux and it did not work. The Toolchain itself is working. 
When i try to build the src.pro to get an library i get this error: /home/df/dev/qt/5.8/android_armv7/mkspecs/features/qt_module_headers.prf:153: error: Cannot write file /include/qmqtt/qmqtt
Depends: Cannot create parent directory
i tried a lot of different pro and qbs files of the project, but is not working. 

when i try to build the src.qbs i get this error: /home/df/.config/QtProject/qtcreator/qbs/1.5.2/profiles/qtc_Android__feba1001/modules/Qt/core/core.qbs:136: error: TypeError: Result of expression 'qbs.toolchain' [undefined] is not an object.

for linux and windows it is working great btw!

thanks for your help!

**Comment by mwallnoefer** [comment]
Sorry I have forgotten to answer this issue. Have you a chance to try with Qt 5.6?

@emqtt/qmqtt-team Any ideas?

**Comment by emqplus** [comment]
@mwallnoefer Really appreciate your contributions on the project. I invited @grutabow to join the project, who is responsible for client side SDK and Edge gateway.

**Comment by grutabow** [comment]
@fuxey  QT's android support is not so good. Please refer to following links which is similar to your problem:
- http://lists.qt-project.org/pipermail/qbs/2016-September/001621.html
- https://bugreports.qt.io/browse/QBS-881
- http://lists.qt-project.org/pipermail/qbs/2015-July/001346.html 

My QT 5.8 on windows has same issue which report that "profile 'qtc_Android__3d01a06d-armv5te' does not exist" and "cpp could not be loaded", even qbs version is 1.7.2. Till now, no solution is found.

Maybe you can refer to the native [android client](https://github.com/emqtt/EMQ-Android-Toolkit).

**Comment by grutabow** [comment]
one more link
https://bugreports.qt.io/browse/QBS-709

**Comment by mwallnoefer** [comment]
Any progress here?
