### ISSUE TITLE
(un)subscribed signal does not pass topic any more

### ISSUE THREAD

**Issue by ejvr** [emqtt/qmqtt#98]
The subscribe signal in QMQTT::Client still has a `topic` argument, but it will always be an empty string.  Apparently the topic is not passed in the `SUBACK` message (See `ClientPrivate::onNetworkReceived`). The same goes for the `unsubscribed` signal.

Personally I do not have problems with this (not using the signals anyway), but I guess it may confuse people. Wouldn't it be better to remove the `topic` variable from the signals? The Client interface was already changed with pull request #96 which introduced the issue, so it seems OK to change it once more.

**Comment by mwallnoefer** [comment]
Good catch! I think it would be better to re-introduce the topic, so that we save it in a member variable. Of course it should be done only if it does not complicate our code too much.

@emqtt/qmqtt-team What do you think?

**Comment by ejvr** [comment]
This could be fixed by introducing a message ID -> topic lookup in the ClientPrivate class. Upon a (un)subscribe we add the message ID/topic combination to the lookup. When the (UN)SUBACK arrives we can recover the topic using the message ID in the message.

This would be a simple fix which would change the ClientPrivate class only. It just tried it and it seemed to work (with mosquitto as the broker). If you want, I can create a pull request with the change.

**Comment by mwallnoefer** [comment]
@ejvr Yes please, I am eager to accept your marvelous contributions.
